package org.example.efm.controller;

import org.example.efm.model.Book;

import javafx.fxml.FXML;
import javafx.scene.control.CheckBox;
import javafx.scene.control.TextField;

public class BookDialogController {

    @FXML
    private TextField titleField;
    @FXML
    private TextField authorField;
    @FXML
    private TextField isbnField;
    @FXML
    private TextField yearField;
    @FXML
    private CheckBox availableCheckBox;

    private Book currentBook;

    public void setBook(Book book) {
        this.currentBook = book;
        if (book != null) {
            titleField.setText(book.getTitle());
            authorField.setText(book.getAuthor());
            isbnField.setText(book.getIsbn());
            yearField.setText(String.valueOf(book.getYear()));
            availableCheckBox.setSelected(book.isAvailable());
        } else {
            // For new book, clear fields (or set defaults)
            titleField.clear();
            authorField.clear();
            isbnField.clear();
            yearField.clear();
            availableCheckBox.setSelected(true);
        }
    }

    public Book getBookFromFields() {
        String title = titleField.getText();
        String author = authorField.getText();
        String isbn = isbnField.getText();
        int year = 0;
        try {
            year = Integer.parseInt(yearField.getText());
        } catch (NumberFormatException e) {
            // Handle invalid year input, perhaps show an error
            System.err.println("Invalid year format: " + yearField.getText());
            // For simplicity, defaulting to 0 or could throw validation error
        }
        boolean available = availableCheckBox.isSelected();

        if (currentBook != null) { // Editing existing book
            currentBook.setTitle(title);
            currentBook.setAuthor(author);
            currentBook.setIsbn(isbn);
            currentBook.setYear(year);
            currentBook.setAvailable(available);
            return currentBook;
        } else { // Creating new book
            // ID will be auto-generated by DB, so pass 0 or handle appropriately in service
            return new Book(0, title, author, isbn, year, available);
        }
    }
}
